[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.20"
remappings = [
    "@openzeppelin-contracts/contracts/=dependencies/@openzeppelin-contracts-5.0.0/",
    "forge-std/=dependencies/forge-std-1.9.0/src/"
]

[dependencies]
"@openzeppelin-contracts" = "5.0.0"
"forge-std" = "1.9.0" 